### ISSUE TITLE
OnMinimize via Click on Taskbar Icon decoration is not properly shown

### ISSUE THREAD

**Issue by SiL3NC3** [laila111111/MetroWindow#1]
**OnMinimize via Click on Taskbar Icon decoration is not properly shown**

To reproduce, what I'm pointing out, just click multiple times on the AppIcon in the taskbar.
If you hold down the left mouse button, the pink border is vanished and the default border is shown.

Also when Window lost focus, the default border is shown.

Any fix for this? Would be appreciated.

**Comment by laila111111** [comment]
As for now I'm unable to reproduce this. I've tried clicking multiple times on the AppIcon in the taskbar and it still behaves as expected. 

When holding down the left mouse button or while the window focus is lost, it actually shows the same glow but in a different color (not the default border), also as expected. You can change this color by setting the resources:

    <SolidColorBrush Color="#434346" x:Key="metroWindowInactiveGlowBrush" />

**Comment by SiL3NC3** [comment]
You are right.
So issue is solved.
Thank you. :)

Am 10.02.2019 um 14:12 schrieb Laïla:

**Comment by laila111111** [comment]
You're welcome :-)
